### ISSUE TITLE
The frame does not adapt to the size of the map

### ISSUE THREAD

**Issue by remiberthoz** [7yl4r/pulsarMap#1]
When entering values manually, if you want a bit of fantasy and map a pulsar too far away, it will get out of the frame : that's sad. I hope you can do something to fix this !

**Comment by 7yl4r** [comment]
Hmm. Yes, I think that may be possible. I'll have to take a look at it. Thanks for the suggestion... I wouldn't want any intergalactic travelers getting lost because some pulsars are out of frame.

**Comment by 7yl4r** [comment]
@TiiXel can you take a look at the manual zoom buttons I added and let me know if those work for what you were trying to do?

**Comment by remiberthoz** [comment]
Hey, thank you for being so fast !
Yes, it works perfectly !

**Comment by 7yl4r** [comment]
Hooray! Don't hesitate to submit more issues if you have any further needs. I've got a lot of big ideas for this project so I think it's hard for me to see the little QoL stuff.
